### ISSUE TITLE
LaunchGUI repo gone? =(

### ISSUE THREAD

**Issue by reallydrained** [TehNut/TehNut#1]
hey man I am trying to learn all I can about (and use) LaunchGUI but all of the links are dead. Cannot access your site, update check URL to .txt file is gone. Just wondering if there is any way I can find this info still. LaunchGUI is really cool and I want to get all I can out of it =D

**Comment by TehNut** [comment]
https://github.com/TehNut-Mods/LaunchGui

**Comment by reallydrained** [comment]
> https://github.com/TehNut-Mods/LaunchGui

THANK YOU! Does this file (https://raw.githubusercontent.com/TehNut/LaunchGui/1.7.10/version.txt) exist somewhere still? Or could you just show me what the text in the file should be? I am trying to figure out the update check URL thing. Thanks bro =D

**Comment by reallydrained** [comment]
Hey dude is there any way you could tell me how the version.txt file is supposed to work? I just need to know what the file is supposed to contain/what the format is. I'd really like to get this working =)

And I'm sorry, I do not mean to be annoying I just can't figure out what it's supposed to be and the documentation for it is gone.
